OpenCMS-DB:
  image: ignatov/docker-oracle-xe-11g
  container_name: OpenCMS-DB
  ports:
    - "15080:8080"
    - "1521:1521"
  stdin_open: true
  volumes:
    - /var/lib/docker/volumes/OpenCMS/DB:/usr/lib/oracle/xe/oradata/XE
    - /var/lib/docker/volumes/OpenCMS/DB:/etc/entrypoint-initdb.d
  tty: true
  labels:
    io.rancher.container.pull_image: always

OpenCMS-App:
  image: sfz-dhub-001.sefaz.al.gov.br:5000/sefaz/sfz-portal-efaz:1.0.0-SNAPSHOT
  container_name: OpenCMS-App
  environment:
    OCSERVER: http://localhost:8088
    DB_USER: system
    DB_PWD: oracle
    DB_DB: opencms
    DB_PRODUCT: oracle
    DB_URL: jdbc:oracle:thin:@10.10.214.10:1521:XE
  stdin_open: true
  volumes:
    - /var/lib/docker/volumes/OpenCMS/App:/var/lib/tomcat8
  tty: true
  links:
    - OpenCMS-DB
  ports:
    - 8088:8080
  labels:
    io.rancher.container.pull_image: always
