OpenCMS-App:
  image: sfz-dhub-001.sefaz.al.gov.br:5000/sefaz/sfz-portal-efaz:1.0.0-SNAPSHOT
  container_name: OpenCMS-App
  environment:
    OCSERVER: http://10.10.214.10:8080
    DB_NAME: opencms
    DB_USER: system
    DB_PWD: oracle
    DB_PRODUCT: oracle
  stdin_open: true
  tty: true
  ports:
    - 8080:8080
  labels:
    io.rancher.container.pull_image: always
